FIXED:  Syntax errors in FindAccountPage.js preventing build from completing.
Please see side-by-side diff for the two errors fixed.  In particular note the second fix, which was made by wrapping everything inside the React component's return statement in a single <div></div> tag. The error preventing build was:

SyntaxError: /Users/dshenoy/Training/OfssaM/titan-crm/src/views/components/accounts/find-account/FindAccountPage.js: Adjacent JSX elements must be wrapped in an enclosing tag (73:12)